# Generated by Django 5.0.6 on 2024-07-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hours',
            field=models.CharField(max_length=100),
        ),
    ]
